### PR TITLE
Make it possible to uninstall, fixes #189

### LINKED ISSUE #189: `rbenv_action` doing nothing
### Cookbook version
2.0.4

### Chef-client version
13.4.24

### Platform Details
Ubuntu 16.04 LTS

### Scenario:
Remove older rubies

### Steps to Reproduce:
```Ruby
# Uninstall old rubies
OLD_RUBIES = %w[2.3.1 2.4.0 2.4.1].freeze
OLD_RUBIES.each do |old_ruby|
  rbenv_ruby old_ruby do
    rbenv_action 'uninstall'
  end
end
```

### Expected Result:
Rubies should get uninstalled.

### Actual Result:
They would get installed, weren't they already installed.

```
  * ruby_rbenv_ruby[2.3.1] action install
    * ruby_rbenv_plugin[ruby-build] action install
      * git[Install ruby-build plugin] action sync (up to date)
       (up to date)
    * apt_package[gcc, autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm3, libgdbm-dev, make] action install (up to date)
     (up to date)
  * ruby_rbenv_ruby[2.4.0] action install
    * ruby_rbenv_plugin[ruby-build] action install
      * git[Install ruby-build plugin] action sync (up to date)
       (up to date)
    * apt_package[gcc, autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm3, libgdbm-dev, make] action install (up to date)
     (up to date)
  * ruby_rbenv_ruby[2.4.1] action install
    * ruby_rbenv_plugin[ruby-build] action install
      * git[Install ruby-build plugin] action sync (up to date)
       (up to date)
    * apt_package[gcc, autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm3, libgdbm-dev, make] action install (up to date)
     (up to date)
```

### PR DESCRIPTION
**Pull request by aried3r**
### Description

Previously it was impossible to uninstall existing Ruby versions because `ruby_installed?` returned `true`, which skipped the action.

But I am not quite sure how to test this. Install, uninstall and assert that `rbenv versions` returns nothing?

### Issues Resolved

#189

### Contribution Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

---
This change is [Reviewable](https://reviewable.io/reviews/sous-chefs/ruby_rbenv/224)

### CODE REVIEW

File: resources/ruby.rb [hunk 1]
```diff
@@ -57,9 +63,21 @@
...
+    not_if { ruby_installed? && new_resource.rbenv_action != 'uninstall' }
+  end
+
+  log_message = new_resource.to_s
+  log_message << if new_resource.rbenv_action == 'uninstall'
+                   ' uninstalled'
+                 else
+                   " build time was #{(Time.now - install_start) / 60.0} minutes"
+                 end
+  Chef::Log.info(log_message)
```
Comment (damacus) [inline resources/ruby.rb:76]: Tidy me up please 👍

**Comment by damacus** [comment]
This is an awesome start!

Your test plan sounds sane to me. I'd only run it on one platform like everything else in `.kitchen.yml` to keep the test suite time down.

File: resources/ruby.rb (hunk 1 above)
Comment (aried3r) [reply resources/ruby.rb:76]: Yeah, I'm not happy with this construct either. How would you like me to resolve this?

File: test/integration/ruby_uninstall/controls/ruby_uninstall.rb [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+system_ruby = '2.5.1'
+user_ruby = '2.5.0'
+
+control 'Global Ruby uninstall' do
+  title 'Global Ruby should be uninstalled'
+
+  desc "#{system_ruby} should be uninstalled"
+  describe bash('source /etc/profile.d/rbenv.sh && rbenv versions --bare') do
+    its('exit_status') { should eq 0 }
+    its('stdout') { should_not match(/#{Regexp.quote(system_ruby)}/) }
```
Comment (aried3r) [inline test/integration/ruby_uninstall/controls/ruby_uninstall.rb]: I cannot get this test to fail, I'm not sure how to access the system wide `rbenv` install.

As `vagrant` I only see the 2.5.0 version:
```console
$ rbenv versions --bare
2.5.0
```

As `root`, I see no Ruby version, although it is installed:
```console
$ ls -halt /usr/local/rbenv/versions/
total 12K
drwxr-xr-x 12 root root 4.0K Aug 20 12:34 ..
drwxr-xr-x  6 root root 4.0K Aug 20 12:34 2.5.1
drwxr-xr-x  3 root root 4.0K Aug 20 12:28 .
```

File: test/integration/ruby_uninstall/inspec.yml [hunk 3]
```diff
@@ -0,0 +1,9 @@
+name: rbenv
+title: rbenv profile
+maintainer: Sous Chefs
+copyright: Webb Agile Solutions Ltd.
```
Comment (aried3r) [inline test/integration/ruby_uninstall/inspec.yml]: I just copied this file from the other suites. Is this still correct?

File: test/integration/ruby_uninstall/inspec.yml [hunk 4]
```diff
@@ -0,0 +1,9 @@
...
+license: Apache-2.0
+summary: Verifies rbenv is installed correctly
```
Comment (aried3r) [inline test/integration/ruby_uninstall/inspec.yml]: Also the summary is the same everywhere, is that intended?

File: test/integration/ruby_uninstall/controls/ruby_uninstall.rb (hunk 2 above)
Comment (aried3r) [reply test/integration/ruby_uninstall/controls/ruby_uninstall.rb]: Maybe it's because mixing system wide install and user install is not a good idea and [discouraged](https://github.com/rbenv/rbenv/issues/38#issuecomment-148413842)

File: test/integration/ruby_uninstall/inspec.yml (hunk 3 above)
Comment (damacus) [reply test/integration/ruby_uninstall/inspec.yml]: If you wrote it as part of your company work, do that.

My copyright can't be on that file

File: test/integration/ruby_uninstall/inspec.yml (hunk 4 above)
Comment (damacus) [reply test/integration/ruby_uninstall/inspec.yml]: I was mostly being lazy with the description, if you want to expand upon it. Feel free to do it in another PR 👍

**Comment by aried3r** [comment]
I removed the copyright (do we have to supply it?) and removed the mix of both system wide and local Ruby installation.

I'm still not _super_ happy with the tests, since I'd rather have setup and assertions interleaved like
```Ruby
rbenv_system_install 'system'
rbenv_ruby system_version
rbenv_global system_version

assert_ruby_is_installed

rbenv_ruby system_version do
  rbenv_action 'uninstall'
end

assert_ruby_is_uninstalled
```

But I guess that's not really possible?

Also I'm not sure how you want me to tidy up the logging, any pointers?

**Comment by aried3r** [comment]
Opening again to maybe trigger Travis again. But I'm not sure it will work if the last commit contains `[ci skip]`.

**Comment by aried3r** [comment]
Btw, https://travis-ci.org/sous-chefs/ruby_rbenv/builds/419181664 worked, but I think it's a commit from before the rebase. :\

**Comment by aried3r** [comment]
Yay! All green

File: resources/ruby.rb (hunk 1 above)
Comment (damacus) [reply resources/ruby.rb:76]: I take it back, the logging here is nice and only triggered on the resource firing. The log resource often just fires every time.

**Comment by damacus** [comment]
Could you cut a release with some CHANGELOG notes and we'll release this?
